src/ExTestTool/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^grappelli/', include('grappelli.urls')),

    url(r'^$', 'onlinetest.views.register'), # register a user
    url(r'^pbyc/(?P<cid>(\d+))/$', 'onlinetest.views.papers_by_college'), #question papers by college
    url(r'^test/(?P<qid>(\d+))/$', 'onlinetest.views.test', name="exam"), # question id
    url(r'^mark/(?P<qid>(\d+))/$', 'onlinetest.views.book_mark', {'add': True}, name='mark'), # bookmark an item
    url(r'^unmark/(?P<qid>(\d+))/$', 'onlinetest.views.book_mark', {'add': False}, name='unmark'), # remove bookmark 
    url(r'^save/$', 'onlinetest.views.store_answer', name='store'), # store answer in session
    url(r'^submit/$', 'onlinetest.views.submit'), # submit paper (saving answers from session)

    url(r'^reports/', 'reports.views.reports'),
    url(r'^save_report/', 'reports.views.save_report'),
    url(r'^report_mode/', 'reports.views.report_mode'),
    url(r'^view_coll_report/', 'reports.views.view_coll_report'),
    url(r'^get_batches/(?P<cid>[\w\d\s]+)/$', 'reports.views.get_batches', name="get_batches")
)

src/onlinetest/models.py
# -*- coding: utf-8 -*-

from django.contrib.auth.models import User
from django.contrib.contenttypes import generic
from django.contrib.contenttypes.models import ContentType
from django.core.exceptions import ValidationError
from django.db import models

from questionbank.models import Option, Category
from questionbank.models import DIQuestion
from questionbank.models import RCQuestion
from questionbank.models import MathQuestion
from questionbank.models import LogicalQuestion
from questionbank.models import SubQuestion


class College(models.Model):
    name = models.CharField(max_length=250)
    street = models.CharField(max_length=250)
    city = models.CharField(max_length=250)
    state = models.CharField(max_length=250)
    contact_no = models.CharField(max_length=12)

    def __unicode__(self):
        return self.name


class Student(models.Model):
    user = models.OneToOneField(User)
    college = models.ForeignKey('College')
    question_paper = models.ForeignKey('QuestionPaper')
    name = models.CharField(max_length=250)
    register_no = models.IntegerField()
    branch = models.CharField(max_length=250)
    email = models.EmailField(max_length=250)
    phone_no = models.CharField(max_length=12)

    def __unicode__(self):
        return self.name


class QuestionPaper(models.Model):
    college = models.ForeignKey('College')
    duration = models.PositiveSmallIntegerField(help_text='Duration of Exam (in minutes)', default=45)
    deployed = models.BooleanField(default=False)

    def __unicode__(self):
        return "Paper %d" % self.id

    def clean(self):
        if len(MathQuestion.objects.order_by('frequency')[:5]) < 5:
            raise ValidationError('Not enough Math Questions in Question Bank')
        if len(DIQuestion.objects.order_by('frequency')[:1])  < 1:            
            raise ValidationError('Not enough Data Interpretation Questions in Question Bank')
        if len(LogicalQuestion.objects.order_by('frequency')[:10]) < 10:
            raise ValidationError('Not enough Logical Questions in Question Bank')
        if len(RCQuestion.objects.order_by('frequency')[:2]) < 2:
            raise ValidationError('Not enough Reading Comprehension Questions in Question Bank')
            

class QuestionItem(models.Model):
    question_paper = models.ForeignKey('QuestionPaper')
    category = models.ForeignKey(Category) # to identify correct Question Type
    question_item = models.ForeignKey(SubQuestion, blank=True, null=True)    
    answer = models.ForeignKey(Option)
    object_id = models.PositiveIntegerField() # stores question here
    content_type = models.ForeignKey(ContentType, related_name="questions")
    content_object = generic.GenericForeignKey(ct_field='content_type', fk_field='object_id')

    def __unicode__(self):
        return "Question%d (Cat: %s, Paper: %d)" % (self.pk, self.category.name, self.question_paper_id)


class AnswerItem(models.Model):
    student = models.ForeignKey(Student)
    question_item = models.ForeignKey(QuestionItem)
    answer = models.ForeignKey(Option)

src/onlinetest/views.py
# from django.contrib.contenttypes.models import ContentType
# from django.db.models import Q, Count, Min
# from django.shortcuts import get_object_or_404, render_to_response
# from django.template import RequestContext
# from django.contrib.admin.views.decorators import staff_member_required

# from questionbank.models import DIQuestion, RCQuestion, MathQuestion, LogicalQuestion, Question, MultiQuestion, SubQuestion, Category, SubCategory
# from onlinetest.models import College, QuestionPaper, Student, AnswerItem
# from questionbank.models import CategorizedQuestion, Option

from collections import defaultdict
import datetime
import json
import random

from django import forms
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render
from django.views.decorators.http import require_POST

from onlinetest.models import AnswerItem
from onlinetest.models import QuestionItem
from onlinetest.models import QuestionPaper
from onlinetest.models import Student
from questionbank.models import CategorizedQuestion
from questionbank.models import MultiQuestion
from questionbank.models import Option
from questionbank.models import SubQuestion
from reports.models import Report

"""
IN_PH = re.compile(
    (?P<std_code>                   # the std-code group
        ^0                          # all std-codes start with 0
        (
            (?P<twodigit>\d{2})   | # either two, three or four digits
            (?P<threedigit>\d{3}) | # following the 0
            (?P<fourdigit>\d{4})
        )
    )
    [-\s]                           # space or -
    (?P<phone_no>                   # the phone number group
        [1-6]                       # first digit of phone number
        (
            (?(twodigit)\d{7})   |  # 7 more phone digits for 3 digit stdcode
            (?(threedigit)\d{6}) |  # 6 more phone digits for 4 digit stdcode
            (?(fourdigit)\d{5})     # 5 more phone digits for 5 digit stdcode
        )
    )
)$, re.VERBOSE)

"""

def register(request):
    """
    Register a user. That's collect informations from him & start the test

    """
    class StudentForm(forms.ModelForm):
        class Meta:
            model = Student
            exclude = ('user', )
            widgets = {
                'college': forms.Select(attrs={'onchange':'FilterQuestionPapers(this);'}),
                'question_paper': forms.Select(attrs={'disabled':'false'}),
            }

    if request.method == 'POST': # If the form has been submitted...
        form = StudentForm(request.POST) # A form bound to the POST data
        if form.is_valid(): # All validation rules pass
            # create a user 
            user = User.objects.create_user(username=form.data['email'], password=form.data['email'], email=form.data['email'])
            user.first_name = form.data['name']
            user.is_staff = False
            user.save()

            # add django user to our student relation
            obj = form.save(commit=False)            
            obj.user = user
            obj.save()

            #logs our temp user in
            user.backend = 'django.contrib.auth.backends.ModelBackend'
            login(request, user)

            # get all question's ids categorywise randomized
            qitems = QuestionItem.objects.filter(question_paper = obj.question_paper).order_by('category', 'object_id', '?').only('id', 'category__name')
            
            # put question ids in session (order will be different for different users)
            request.session['qids'] = [q.id for q in qitems]

            # get starting items of each category
            cat_beg = defaultdict(list)
            for q in qitems:
                cat_beg[q.category.name].append(int(q.id))

            # set initial qids for each category in session
            request.session['cat_beg'] = cat_beg

            # set start & end time in session (of test)
            started_at = datetime.datetime.now()
            should_end_at = started_at + datetime.timedelta(minutes=int(obj.question_paper.duration)) 
            request.session['started_at'] = started_at
            request.session['should_end_at'] = should_end_at

            #redirect to test home page
            return HttpResponseRedirect('/test/%s/' % qitems[0].id) # Redirect after POST
    else:
        form = StudentForm() # An unbound form
    # display registration form and instructions
    return render(request, 'register.html', {'form': form,})

def papers_by_college(request, cid):
    question_papers = QuestionPaper.objects.filter(college__id=cid)
    data = {question_paper.pk: str(question_paper) for question_paper in question_papers if question_paper.deployed}
    return HttpResponse(json.dumps(data), mimetype="application/json")

@login_required(login_url='/') # add a page which says session expiered
@user_passes_test(lambda u: not u.is_staff)
def test(request, qid):
    '''
    qid: QuestionItem ID, which we will compare against the one in session 
    sqid: SubQuestion ID for MultiQuestion types (RC, DI), default [None]
    '''
    if not long(qid) in request.session.get('qids', []):
        return HttpResponse("Huh, Playing with me?")

    now = datetime.datetime.now()
    if not (now < request.session['should_end_at'] and now > request.session['started_at']):
       return HttpResponseRedirect('/submit/') # Exam time is over, let's submit it.

    # time management
    remaining_time = request.session['should_end_at'] - now
    remaining_minutes = "%02d" % (remaining_time.seconds / 60, )
    remaining_seconds = "%02d" % (remaining_time.seconds % 60, )

    # get QuestionItem
    qitem = QuestionItem.objects.get(pk=qid)
    question_obj = qitem.content_object
    data = None
    question = None
    options = []

    # now populate question, options and data(optional)
    if isinstance(question_obj, CategorizedQuestion):
        question = question_obj.question
        options.insert(0, question_obj.correct)
        options.insert(0, question_obj.option1)
        options.insert(0, question_obj.option2)
        options.insert(0, question_obj.option3)

    if isinstance(question_obj, MultiQuestion):
        data = question_obj.data
        sub_question = qitem.question_item
        question = sub_question.question
        options.insert(0, sub_question.correct)
        options.insert(0, sub_question.option1)
        options.insert(0, sub_question.option2)
        options.insert(0, sub_question.option3)
    
    # Position of correct option
    options_pos = request.session.get(qid, None)
    if not options_pos:
        random.shuffle(options) #shuffle options
        options_pos = {i: j for i,j in enumerate(options)}
        request.session[qid] = options_pos

    # next and previous questions
    qids = request.session['qids'] # by now we can assume qids is in session
    indx = qids.index(long(qid)) # also we can assume qid is in the qids list
    next = qids[indx+1] if indx<len(qids)-1 else None # len()-1 will be last index
    prev = qids[indx-1] if indx>0 else None # 0 is first inde

    # How many answerd
    student = Student.objects.get(user=request.user)
    answerd = AnswerItem.objects.filter(student=student).count()

    #if an option is previosuly answered we have to select it by default
    sel_opt = None
    try:
        qi = QuestionItem.objects.get(pk=qid)
        a = AnswerItem.objects.get(student=student, question_item=qi)
        sel_opt = a.answer_id
    except:
        pass

    bundle = {
        'cur': str(int(qid)),
        'next': next,
        'prev': prev,
        'remaining_minutes': remaining_minutes,
        'remaining_seconds': remaining_seconds,
        'para': data,
        'question': question,
        'options': options_pos,
        'cat_beg': dict(request.session['cat_beg']),
        'bookmarks': request.session.get('bookmarks', []),
        'answerd': answerd,
        'sel_opt': sel_opt,
    }
    return render(request, 'exam.html', bundle)

def book_mark(request, qid, add):
    bookmarks = request.session.get('bookmarks', [])
    qids = request.session['qids']
    if long(qid) in qids:
        if add:
            if qid not in bookmarks: bookmarks.insert(0, qid)
        else:
            if qid in bookmarks: bookmarks.remove(qid)

    request.session['bookmarks'] = bookmarks
    return HttpResponseRedirect('/test/%s' % qid) # redirect to same page

@require_POST
def store_answer(request):
    class AnswerItemForm(forms.ModelForm):
        class Meta:
            model = AnswerItem
            exclude = ('student', )

    form = AnswerItemForm(request.POST)
    if form.is_valid(): # All validation rules pass 
        student = Student.objects.get(user=request.user)
        try:
            question_item = QuestionItem.objects.get(pk=form.data['question_item'])
            answer = Option.objects.get(pk=form.data['answer'])
        except:
            data = {'msg': 'error'}
            return HttpResponse(json.dumps(data),mimetype="application/json") # Why this Kolavery da? we got malformed data

        obj = AnswerItem()
        try:
            obj = AnswerItem.objects.get(student=student, question_item=question_item)
        except AnswerItem.DoesNotExist:
            obj = AnswerItem()
            obj.student = student
            obj.question_item = question_item
        finally:
            obj.answer = answer
            obj.save()
        
        data = {'msg': 'success'}
        return HttpResponse(json.dumps(data),mimetype="application/json")

    data = {'msg': 'validationerror'}
    return HttpResponse(json.dumps(data),mimetype="application/json")

def submit(request):
    student = Student.objects.get(user=request.user)
    attempts = AnswerItem.objects.filter(student=student).order_by('question_item__category')

src/onlinetest/templates/base.html
{% load static %}
{% get_static_prefix as STATIC_PREFIX %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>ExTest: Expicient e-Test</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="Tool to conduct online tests.">
        <meta name="author" content="Arun K. R.<arun.rajeevan@expicient.com>">

        <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
        <!--[if lt IE 9]>
          <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->

        <link href="{{ STATIC_PREFIX }}bootstrap/css/bootstrap.min.css" rel="stylesheet">
        <link href="{{ STATIC_PREFIX }}bootstrap/css/bootstrap-responsive.min.css" rel="stylesheet">

        {% block headerstyle %}{% endblock %}
        {% block headerjs %}{% endblock %}
    </head>

    <body ondragstart="return false" onselectstart="return false">
        {% block titlebar %}
        <!-- Navbar
        ================================================== -->
        <div class="navbar navbar-static-top">
            <div class="navbar-inner">
                <a class="brand" href="../">Expicient e-Test</a>
                {% block navs %} {% endblock %}
            </div>
        </div>
        {% endblock %}

        <div class="container">
            {% block content %}{% endblock %}

            {% block footer %}
            <hr />
            <footer class="footer">
                <p class="pull-right">&copy; All rights reserved Expicient Inc. 2012</a></p>
            </footer>
            {% endblock %}

        </div><!-- /container -->
         
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>
        <script src="{{ STATIC_PREFIX }}bootstrap/js/bootstrap.min.js"></script>

        {% block bodyjs %}{% endblock %}

        {% block norightclickjs %}
        <script> 
            var message="Function Disabled!"; 
            function clickIE4(){ 
                if (event.button==2){ 
                    //alert(message); 
                    return false; 
                } 
            } 
            function clickNS4(e){ 
                if (document.layers||document.getElementById&&!document.all){ 
                    if (e.which==2||e.which==3){ 
                        //alert(message); 
                        return false; 
                    } 
                } 
            } 
            if (document.layers){ 
                document.captureEvents(Event.MOUSEDOWN); 
                document.onmousedown=clickNS4; 
            } else if (document.all&&!document.getElementById){ 
                document.onmousedown=clickIE4; 
            } 
            document.oncontextmenu=new Function("return false") 
        </script>
        {% endblock %}    
    </body>    
</html>

src/onlinetest/templates/exam.html
{% extends "base.html" %}

{% block navs %}
<ul class="nav">
    <li class="divider-vertical"></li>
    {% for key, val in cat_beg.iteritems %}
        {% if val %}
            <li {% if cur in val %}class="active"{% endif %}><a href="{% url onlinetest.views.test qid=val.0 %}">{{ key }}</a></li>
        {% endif %}
    {% endfor %}
</ul>
<ul class="nav pull-right">
    <li class="dropdown">
        <a class="dropdown-toggle" role="menu" data-toggle="dropdown" data-target="#" href="#"> 
            Book Marks <b class="caret"></b>
        </a>
        <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel" id="bookmarks">
            {% for item in bookmarks %}
                <li><a href="{% url exam qid=item %}">Bookmark{{forloop.counter}}</a></li>
            {% endfor %}
        </ul>
    </li>
</ul>
{% endblock %}

{% block content %}
<section id="content">
    <br />
    <div class="row">
            <div class="span3">
                <p id="counter"></p>
                <!-- {{ request.session.should_end_at|timeuntil }} more -->
                <br />
                <div class="well"> {{ answerd }} out of 30 question attempted.</div>                
                <br />
                <a class="btn btn-warning btn-large" href="{% url onlinetest.views.submit %}">End Test</a>
            </div>

            <div class="span9"> 
                <div class="flash">
                    <div class="alert" id="holder"></div>
                </div>
                {% if cur in bookmarks %}
                    <a class="btn btn-info pull-right" href="{% url unmark qid=cur %}">Un BookMark</a>
                {% else %}
                    <a class="btn btn-primary pull-right" href="{% url mark qid=cur %}">BookMark</a>
                {% endif %}

                {% if para %} {{ para|safe|escape }} <br /> {% endif %}

                {{ question|safe|escape }} <br />

                <form action="#" method="post" id="answerme">{% csrf_token %}
                    <div style='display:none'><input type='hidden' name='question_item' value='{{ cur }}' /></div>
                    <div class="controls">
                        <label class="radio">
                            <input type="radio" name="answer" value="{{ options.0.pk }}" {% if sel_opt %}{% if sel_opt == options.0.pk %} checked {% endif %}{% endif %} /> 
                            {{ options.0.answer|safe|escape }}
                        </label>
                        <label class="radio">
                            <input type="radio" name="answer" value="{{ options.1.pk }}" {% if sel_opt %}{% if sel_opt == options.1.pk %} checked {% endif %}{% endif %} />
                            {{ options.1.answer|safe|escape }}
                        </label>
                        <label class="radio">
                            <input type="radio" name="answer" value="{{ options.2.pk }}" {% if sel_opt %}{% if sel_opt == options.2.pk %} checked {% endif %}{% endif %} />
                            {{ options.2.answer|safe|escape }}
                        </label>
                        <label class="radio">
                            <input type="radio" name="answer" value="{{ options.3.pk }}" {% if sel_opt %}{% if sel_opt == options.3.pk %} checked {% endif %}{% endif %} />
                            {{ options.3.answer|safe|escape }}
                        </label>
                    </div>
                </form>

                <br />
                <ul class="pager">
                    {% if prev %}
                    <li class="previous">
                        <a href="{% url exam qid=prev %}">&larr; Prev</a>
                    </li>
                    {% else %}
                    <li class="previous disabled">
                        <a href="#">&larr; Prev</a>
                    </li>
                    {% endif %}

                    {% if next %}
                    <li class="next">
                        <a href="{% url exam qid=next %}">Next &rarr;</a>
                    </li>
                    {% else %}
                    <li class="next disabled">
                        <a href="#">Next &rarr;</a>
                    </li>
                    {% endif %}
                </ul>

            </div> <!-- span9 -->

        </div> <!-- row -->
        {{ len }}
</section>
{% endblock %}

{% block bodyjs %} 
<script src="{{ STATIC_PREFIX }}countdown/js/jquery.countdown.min.js"></script>
<script>
    $(function(){
        $('.flash').click(function() { $(this).fadeOut('slow'); return false; });
        $('.flash').hide();

        // counter logic
        $('#counter').countdown({
            image: '{{ STATIC_PREFIX }}countdown/img/digits.png',
            startTime: '{{ remaining_minutes }}:{{ remaining_seconds }}',
            timerEnd: function(){ alert('end!'); },
            format: 'mm:ss'
        });

        // answer persistance logic
        $('input[name=answer]').change(function(){
            $.ajax({
                url: '{% url store %}',
                type: 'post',
                dataType: 'json',
                data: $('#answerme').serialize(),
                success: function(data) {
                    if(data['msg'] === 'success'){
                        //show success
                        var obj = $('#holder');
                        obj.text('Your selection saved.');
                        obj.addClass('alert-success').removeClass('alert-error');
                    }else{
                        //show error
                        var obj = $('#holder');
                        obj.text(data['msg']);                        
                        obj.addClass('alert-error').removeClass('alert-success');
                    }
                    if($('#holder').html()!=''){$('.flash').slideDown('slow');}
                }
            });
        });
        
    });
</script>
{% endblock %}

src/onlinetest/templates/register.html
{% extends "base.html" %}

{% block content %}
<section id="content">
    <div class="page-header">
        <h1>Register</h1>
        <p class="lead">Please read the instructions and fill in your details to start the Test</p>
    </div>
    <div class="row">
        <div class="span8">
            <p> Read the instructions creafully before filling out the registration form.
                <ul>
                    <li>Once you filled the registration form, exam will be started.</li>
                    <li>Do not close the browser once exam is started.</li>
                    <li>Exam will be closed automatically after given exam period (usually 45min).</li>
                    <li>You can End exam at any point of time. This action is not revokable.</li>
                    <li>Use your own email address, as it's used later to contact you and to uniquely identify you.</li>
                </ul>
            </p>
            <p>
                <ul>
                    <li>Every correct answer adds 1 point to your total.</li>
                    <li>Every incorrect answer will reduce 0.25 point from your total.</li>
                    <li>There will be a total of 30 questions.</li>
                </ul>
            </p>
            <p> Good Luck you champ :)</p>
        </div>
        <div class="span4">
            <form action="" method="post">{% csrf_token %}
                {% for field in form %}
                    <div class="fieldWrapper">
                        {{ field.errors }}
                        {{ field.label_tag }}
                        {{ field }}
                    </div>
                {% endfor %}
                <input class="btn btn-large btn-primary" type="submit" value="Start the test" />
            </form>
        </div>
    </div>
</section>
{% endblock %}

{% block bodyjs %}
<script> 
    function FilterQuestionPapers(){ 
        var questionPaperList = $('#id_question_paper'); //get question_paper dropdown
        questionPaperList.html(''); //remove every options
        questionPaperList.append(new Option('Loading...', '-1', false, false));
        questionPaperList.attr('disabled', 'disabled');
        var collegeList = $('#id_college');
        var cid = collegeList.val();

        if(cid>0){
            $.getJSON('/pbyc/' + cid + '/', function(data) {
                var count = 0;
                questionPaperList.html(''); //remove every options                    
                $.each(data, function(key, val) {
                    questionPaperList.append(new Option(val, key, false, false));
                    count += 1;
                });

                if(count > 0){
                    questionPaperList.removeAttr('disabled');
                }else{
                    questionPaperList.html(''); //remove every options
                    questionPaperList.append(new Option('No deployed tests', '-1', false, false));
                }
                
            });
        }else{
            questionPaperList.html(''); //remove every options                    
            questionPaperList.append(new Option('Select College', '-1', false, false));
            questionPaperList.attr('disabled', 'disabled');
        }
    }
    $(document).ready(function() {
        FilterQuestionPapers();
    });
</script>
{% endblock %}